### ISSUE TITLE
implement categories from a static list

### ISSUE THREAD

**Issue by timofeysie** [timofeysie/khipu#3]

**Comment by timofeysie** [comment]
See notes for this task in the [readme](https://github.com/timofeysie/khipu#implement-categories-from-a-static-list)

**Comment by timofeysie** [comment]
Here is a sample JSON entry for a category from the Tiwanaku project:
```
{
        "cognitive_bias": "http://www.wikidata.org/entity/Q18570",
        "cognitive_biasLabel": "Hawthorne effect",
        "cognitive_biasDescription": "social phenomenon",
        "lang": "en"
    }
```

**Comment by dhananjaya90** [comment]
@timofeysie I just added categories component, and build a hardcoded list with predetermined categories. I kept them in the environment file for now.

**Comment by timofeysie** [comment]
Issue #15 was opened related to this work.
